"use strict"

// The base rule set

module.exports = {
    extends: ["eslint:recommended"],
    rules: {
        "no-array-constructor": 2,
        "no-caller": 2,
        "no-catch-shadow": 0,
        "no-console": 0,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-floating-decimal": 2,
        "no-implied-eval": 2,
        "no-invalid-this": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-lone-blocks": 2,
        "no-lonely-if": 2,
        "no-loop-func": 2,
        "linebreak-style": [2, "unix"],
        "no-multi-spaces": 2,
        "no-multi-str": 2,
        "no-multiple-empty-lines": [2, {max: 1}],
        "no-native-reassign": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new-wrappers": 2,
        "no-octal-escape": 2,
        "no-proto": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-shadow-restricted-names": 2,
        "no-spaced-func": 2,
        "no-trailing-spaces": 2,
        "no-throw-literal": 2,
        "no-undef-init": 2,
        "no-unneeded-ternary": 2,
        "no-unused-expressions": 2,
        "no-use-before-define": [2, "nofunc"],
        "no-useless-call": 2,
        "no-void": 2,
        "no-warning-comments": 1, // The only warning
        "no-with": 2,

        "array-bracket-spacing": 2,
        "block-spacing": 2,
        "brace-style": [2, "1tbs", {allowSingleLine: true}],
        "camelcase": 2,
        "comma-dangle": [2, "always-multiline"],
        "comma-spacing": 2,
        "comma-style": 2,
        "consistent-this": [2, "self"],
        "curly": [2, "multi-line"],
        "dot-location": [2, "property"],
        "dot-notation": 2,
        "eol-last": 2,
        "eqeqeq": [2, "allow-null"],
        "func-style": [2, "declaration"],
        "guard-for-in": 2,
        "indent": [2, 4],
        "key-spacing": 2,
        "max-depth": 2,
        "max-len": [2, 80, 4],
        "max-nested-callbacks": [2, 4],
        "max-statements": [2, 25],
        "new-parens": 2,
        "object-curly-spacing": 2,
        "one-var": [2, {initialized: "never"}],
        "operator-assignment": 2,
        "operator-linebreak": [2, "after", {
            overrides: {"?": "before", ":": "before"},
        }],
        "padded-blocks": [2, "never"],
        "quote-props": [2, "as-needed"],
        "quotes": [2, "double", "avoid-escape"],
        "radix": 2,
        "semi": [2, "never"],
        "space-after-keywords": 2,
        "space-before-keywords": 2,
        "space-before-function-paren": [2, {
            anonymous: "always",
            named: "never",
        }],
        "space-in-parens": 2,
        "space-infix-ops": [2, {int32Hint: true}],
        "space-unary-ops": 2,
        "spaced-comment": [2, "always"],
        "strict": [2, "function"],
        "wrap-iife": [2, "inside"],

        // Mostly Node-specific stuff that translates well to other runtimes as
        // well.
        "callback-return": 2,
        "handle-callback-err": [2, "^(err|error)$"],
    },
}
